name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: mcos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./Pomodoro
        run: npm install

      - name: Run Linting
        working-directory: ./Pomodoro
        run: npm run lint

      - name: Build App
        working-directory: ./Pomodoro
        run: |
          npx react-native run-ios --configuration Release
